# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a63ddb4a45944e80b6451c870d46a3bfd682d63d0be9088d87f5d6c673eff6b8779c2b7809dd8d576b306f0400cb3e23c12e1f38de65714f446aeac9bdccf298

test:
  secret_key_base: da5b2f7f6995759b32d8ff9c0723e3aeaa413abea9bbadeb9775ce4b001ddcb2f72561196eb542b1c7c6bcf8b6858e78621bc491d7a7fdb1bfeb86b5b11cf270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
